name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm dnsmasq iproute2 isc-dhcp-client libpcap-dev ntfs-3g openssh-client openvswitch-switch qemu-kvm qemu-utils

    - name: testing
      id: testing
      run: |
          ls -lah /lib/x86_64-linux-gnu/

    - name: Build RPM package
      id: rpm
      run: |
        chmod +x ./packaging/rpm/build.bash

        export PCAPV=1.9.1
        wget http://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
        tar xvf libpcap-$PCAPV.tar.gz
        pushd libpcap-$PCAPV
        ./configure --with-pcap=linux
        make
        popd

        export LD_LIBRARY_PATH="-L/usr/lib/x86_64-linux-gnu/libpcap-$PCAPV"
        export CGO_LDFLAGS="-L/usr/lib/x86_64-linux-gnu/libpcap-$PCAPV"
        export CGO_CPPFLAGS="-I/usr/lib/x86_64-linux-gnu/libpcap-$PCAPV"
        CGO_ENABLED=1 bash packaging/rpm/build.bash
        ldd bin/minimega

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: minimega-rpm
        path: ./packaging/rpm/rpmbuild/RPMS/*
