name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm dnsmasq iproute2 isc-dhcp-client libpcap-dev ntfs-3g openssh-client openvswitch-switch qemu-kvm qemu-utils

    - name: Build RPM package
      id: rpm
      run: |
        chmod +x ./packaging/rpm/build.bash
        # Set the compiler and linker flags
        export CGO_CFLAGS="-I/usr/include"
        export CGO_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -l:libpcap.so"

        # Optionally set the library path for runtime
        export LD_LIBRARY_PATH="/usr/lib64:$LD_LIBRARY_PATH"

        CGO_ENABLED=1 bash packaging/rpm/build.bash
        ldd bin/minimega

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: minimega-rpm
        path: ./packaging/rpm/rpmbuild/RPMS/*
